### ISSUE TITLE
@navikt/nap-pakker deprecates

### ISSUE THREAD

**Issue by erlendev** [navikt/familie-ef-sak-frontend#314]
Hei

Ser dere har dependencies til noen pakker som vi på SIF (Sykdom i familien)-området har publisert på npmjs.com gjennom repoet [not-a-platform](https://github.com/navikt/not-a-platform) - `nap-header`, `nap-popover` og `nap-user-panel`. 

Not-a-platform har ikke noe naturlig hjem idag, og disse pakkene er som følge av det tenkt deprecated til fordel for pakker som vi i SIF publiserer på GitHub sitt pakkeregistry gjennom repoet [k9-frontend-modules](https://github.com/orgs/navikt/packages?repo_name=k9-frontend-modules). Det betyr ikke at dere ikke kan fortsette å bruke de som ligger på npmjs (de unpublishes ikke), men de gamle pakkene vil ikke bli vedlikeholdt fra vår side, og repoet er tenkt arkivert.

De komponentene dere har avhengigheter til ligger tilgjengelig og er så og si uendret i pakken @navikt/k9-react-components, men denne ligger per idag kun publisert på GitHub sitt pakkeregistry. Dere står selvfølgelig fritt til å ta den i bruk, men de vil kunne endre seg utifra behov man har på K9-området.

Bare å ta kontakt med meg på Slack eller tagge meg på GitHub/svare opp issue :)

**Comment by eirarset** [comment]
Hei og takk for info!

Vi bruker ikke pakkene, men ser at de fortsatt ligger som deps 📦  Det skal vi rydde opp i.
