### ISSUE TITLE
Cache av security-token-service token.

### ISSUE THREAD

**Issue by ybelMekk** [navikt/familie-ef-sak-frontend#49]
Har lagd et bord i grafana som teller antall unike brukere som requester token, og antall ggr en app gjør de. Et token i rest-sts er gylig i 1 time. 3600 sec.

https://grafana.adeo.no/d/qqBj7ghmk/security-token-service?orgId=1&var-datasource=prod-fss&var-app=security-token-service&var-namespace=default&var-docker_image=89b22648464707f001e726916bfef11bc2f78f32&var-ingress_url=All&var-interval=$__auto_interval_interval&from=1604321411367&to=1604407811368

Har dere mulighet å se på caching da dette de ser ut som srvbruker: `srvfamilie-ks-opps` har spurt etter 290k tokens i et tidsrum på 8 dager, hvilket ikke er holdbart hvis et token lever i 1 time.

**Comment by charliemidtlyng** [comment]
Dette ble fikset en gang før jul.
